import React,{useEffect} from 'react'
import {ArrowLeft,ArrowUpRight} from 'lucide-react'
import './industrial-design-page.css'

const dimensions=[
 ['01','功能架构','FUNCTION','把使用流程、零部件关系、接口、维护与收纳组织成清晰系统，使形态服务于真实任务。'],
 ['02','人机尺度','ERGONOMICS','从身体姿态、握持、触达、视角、用力与疲劳出发，让产品在连续使用和极端场景中依然自然。'],
 ['03','形态语言','FORM','通过比例、体块、曲面、分割与细节建立秩序，使产品的性格、性能与品牌被准确感知。'],
 ['04','材料与工艺','CMF','让颜色、材料、表面处理和触感回应成本、耐久、清洁、安全与情绪价值，而非停留在装饰。'],
 ['05','结构制造','DFM','在概念阶段同步考虑壁厚、拔模、装配、散热、线束、紧固与供应链能力，让方案能够被稳定生产。'],
 ['06','验证迭代','VALIDATION','通过草模、手板、人机测试、结构评审与样机反馈不断修正，在真实约束中提升方案完成度。']
]
const cases=[
 {no:'01',title:'游戏手柄',en:'BODY × CONTROL',lead:'握持不是轮廓问题，而是手掌、手指与操作节奏共同决定的动态关系。',body:'围绕长时间游戏场景，我把设计重点放在掌心支撑、扳机触达、按键分区与重心感受。造型通过连续主曲面建立包裹感，再用局部切面和色彩分区强化操作区域。识别度不是额外贴附的符号，而是由握持结构自然生成的产品性格。',a:'/industrial-3c/industrial-02.png',b:'/industrial-3c/industrial-06.png'},
 {no:'02',title:'机场跑道检测设备',en:'SYSTEM × RELIABILITY',lead:'专业设备的形态，首先要让状态、方向、维护和可靠性一目了然。',body:'机场跑道检测面对移动作业、户外环境和专业维护。方案从检测模块、支撑结构、视窗与防护关系出发，用明确的体块层级表达功能架构；关键接触、运动和维护区域保持可识别，使设备既具技术感，也传递耐久、精密与可信赖的专业语义。',a:'/industrial-3c/industrial-24.png',b:'/industrial-3c/industrial-27.png'},
 {no:'03',title:'家用扫地机器人',en:'HOME × INTEGRATION',lead:'进入家庭的技术产品，需要降低设备侵入感，同时保留清晰的使用反馈。',body:'家庭清洁产品长期处于居住空间中，除了效率，还涉及收纳、清洁维护、视觉融入与使用门槛。我通过克制的几何关系和家居化 CMF 弱化机械感，并让尘盒、按键、传感与维护路径保持直观；外观安静，但功能状态不能模糊。',a:'/industrial-3c/industrial-44.png',b:'/industrial-3c/industrial-47.png'},
 {no:'04',title:'高能量激光治疗仪',en:'MEDICAL × TRUST',lead:'医疗设备的高级感来自安全、清晰和专业，而不是复杂造型。',body:'治疗设备同时面对医生、患者、诊疗空间和严格的使用约束。我把屏幕视角、手柄握持、配件收纳、移动稳定、清洁维护与散热共同纳入整机设计，以连续而克制的体块降低压迫感，用深色功能区建立操作焦点，在效率、安全和信任之间形成统一语言。',a:'/medical/laser-ppt/laser-17.png',b:'/medical/laser-ppt/laser-18.png'},
 {no:'05',title:'耳温测量仪',en:'DETAIL × USABILITY',lead:'小型手持设备的品质，往往由毫米级的人机与细节决定。',body:'耳温仪覆盖医护与家庭用户，也包含儿童夜间测量等低能见度场景。设计通过手柄直径、探头夹角、按键位置和屏幕方向测试降低腕部负担与误操作；柔和曲面建立亲和感，局部光效和界面层级则提供明确状态反馈。',a:'/medical/ear-ppt/ear-19.png',b:'/medical/ear-ppt/ear-20.png'}
]
const process=[['DISCOVER','场景研究','观察人、物与环境的关系'],['DEFINE','设计策略','形成核心问题与产品语言'],['DEVELOP','概念迭代','草图、建模、CMF 与结构并行'],['VALIDATE','原型验证','检验人机、装配和体验风险'],['DELIVER','设计落地','深化细节并连接工程与供应链']]

export default function IndustrialDesignPage(){
 useEffect(()=>{scrollTo(0,0);const es=document.querySelectorAll('[data-id-reveal]');const o=new IntersectionObserver(xs=>xs.forEach(x=>x.target.classList.toggle('show',x.isIntersecting)),{threshold:.12,rootMargin:'0px 0px -7%'});es.forEach(e=>o.observe(e));return()=>o.disconnect()},[])
 return <main className="idp">
  <header className="idp-nav"><a href="/#strengths"><ArrowLeft/> 返回职业能力</a><nav><a href="#view">方法</a><a href="#cases">作品</a><a href="#process">流程</a></nav></header>
  <section className="idp-hero"><div className="idp-motion" aria-hidden="true"><svg viewBox="0 0 1600 900" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="idpWire" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#bdff39"/><stop offset=".48" stopColor="#7fc98b"/><stop offset="1" stopColor="#6dcec7"/></linearGradient><radialGradient id="idpAura"><stop offset="0" stopColor="#88bb72" stopOpacity=".22"/><stop offset="1" stopColor="#07100b" stopOpacity="0"/></radialGradient></defs><circle className="idp-cad-aura" cx="1160" cy="430" r="360"/><g className="idp-cad-orbits"><ellipse cx="1160" cy="430" rx="360" ry="205"/><ellipse cx="1160" cy="430" rx="275" ry="150"/><ellipse cx="1160" cy="430" rx="190" ry="96"/></g><g className="idp-cad-assembly"><path className="idp-cad-part idp-cad-part-a" d="M966 344C1023 278 1138 244 1237 268C1306 285 1355 326 1365 377C1373 420 1344 454 1291 470C1202 497 1072 483 995 434C953 407 940 375 966 344Z"/><path className="idp-cad-part idp-cad-part-b" d="M997 459C1080 504 1205 516 1291 489L1270 569C1256 617 1201 647 1137 631C1068 614 1007 568 978 516Z"/><path className="idp-cad-seam" d="M1004 397C1091 349 1239 342 1328 386M1007 465C1090 424 1228 420 1298 451M1035 523C1105 557 1196 569 1261 546"/><path className="idp-cad-axis" d="M914 430H1428M1160 176V692"/><g className="idp-cad-nodes"><circle cx="966" cy="344" r="5"/><circle cx="1365" cy="377" r="5"/><circle cx="1291" cy="489" r="5"/><circle cx="1137" cy="631" r="5"/><circle cx="978" cy="516" r="5"/></g></g><g className="idp-cad-measure"><path d="M895 265H1415M895 252V278M1415 252V278"/><path d="M1444 303V626M1431 303H1457M1431 626H1457"/><text x="1122" y="246">520 / FORM ENVELOPE</text><text x="1468" y="473" transform="rotate(90 1468 473)">323 / ASSEMBLY</text></g><g className="idp-cad-ghost"><path d="M873 327C991 198 1230 156 1407 241"/><path d="M903 598C1056 731 1301 704 1430 579"/></g></svg><div className="idp-scan"/><div className="idp-index"><span>01</span><span>02</span><span>03</span><span>04</span></div></div><div className="idp-shade"/><p>INDUSTRIAL DESIGN / 02</p><h1>工业<br/><i>设计</i></h1><div><h2>让功能、身体与制造，<br/>在同一种产品语言中相遇。</h2><span>我把工业设计理解为对复杂约束的可见化组织：不仅塑造外观，也决定产品如何被理解、握持、操作、维护、制造与长期使用。</span></div></section>
  <section className="idp-intro idp-shell" data-id-reveal><p>MY DESIGN VIEW</p><h2>好形态不是被“画”出来的，<br/>而是从场景与约束中生长出来。</h2><div>从电子 3C、文创和设备，到医疗产品与产品管理，我持续在用户需求、商业目标、品牌表达和制造实现之间寻找平衡。对我而言，工业设计不是最后一道美化工序，而是从产品定义开始，贯穿人机、结构、CMF、工程协作与量产落地的整合能力。</div></section>
  <section className="idp-dim idp-shell" id="view"><header data-id-reveal><p>01 / DESIGN DIMENSIONS</p><h2>六个维度，构成一件<br/>完整的实体产品。</h2></header><div>{dimensions.map(x=><article key={x[0]} data-id-reveal><span>{x[0]}</span><small>{x[2]}</small><h3>{x[1]}</h3><p>{x[3]}</p></article>)}</div></section>
  <section className="idp-quote"><p>FORM IS NOT THE END.<br/><i>IT IS EVIDENCE OF DECISIONS.</i></p></section>
  <section className="idp-cases idp-shell" id="cases"><header data-id-reveal><p>02 / SELECTED PRACTICE</p><h2>不同品类，<br/>同一套设计判断。</h2></header>{cases.map((x,i)=><article className={i%2?'reverse':''} key={x.no} data-id-reveal><div className="idp-media"><img src={x.a} alt={`${x.title}设计图`}/><img src={x.b} alt={`${x.title}细节或效果图`}/></div><div className="idp-copy"><span>{x.no} / {x.en}</span><h3>{x.title}</h3><b>{x.lead}</b><p>{x.body}</p></div></article>)}</section>
  <section className="idp-process" id="process"><div className="idp-shell"><header data-id-reveal><p>03 / WORKFLOW</p><h2>发散与收敛反复发生，<br/>直到方案足够清晰。</h2></header><div className="idp-flow">{process.map((x,i)=><article key={x[0]} data-id-reveal><span>{String(i+1).padStart(2,'0')}</span><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
  <section className="idp-principles idp-shell" data-id-reveal><p>DESIGN PRINCIPLES</p><h2>我的工业设计判断标准</h2><div><span>功能关系是否清晰</span><span>人机动作是否自然</span><span>形态语言是否一致</span><span>细节是否能够制造</span><span>产品是否适合环境</span><span>价值是否能被感知</span></div></section>
  <section className="idp-sources idp-shell" data-id-reveal><p>METHOD REFERENCES</p><h2>方法参考</h2><a href="https://www.designcouncil.org.uk/resources/the-double-diamond/" target="_blank" rel="noreferrer">Design Council · Double Diamond <ArrowUpRight/></a><a href="https://www.autodesk.com/products/fusion-360/design-for-manufacturing" target="_blank" rel="noreferrer">Autodesk · Design for Manufacturing <ArrowUpRight/></a><a href="https://www.fda.gov/medical-devices/human-factors-and-medical-devices/human-factors-considerations" target="_blank" rel="noreferrer">FDA · Medical Device Human Factors <ArrowUpRight/></a></section>
  <footer className="idp-footer"><h2>DESIGN FOR USE.<br/>DESIGN FOR MAKING.</h2><a href="/industrial">查看电子 3C 与多品类作品 <ArrowUpRight/></a></footer>
 </main>
}
