import { ArrowLeft } from 'lucide-react'
import './medical.css'
const details={
 laser:{no:'01',title:'高能量\n激光治疗仪',en:'HIGH-ENERGY LASER THERAPY DEVICE',hero:'/medical-hero/laser.jpg',lead:'从高频临床操作出发，重新定义治疗设备体验。',intro:'围绕医院、康复中心与临时站点的真实使用流程，优化屏幕交互、手柄持握、配件收纳与快速清洁，并以紧凑、专业且可信赖的视觉语言完成整机设计。',images:['/medical/page-013.webp','/medical/page-021.webp']},
 ear:{no:'02',title:'耳温\n测量仪',en:'EAR TEMPERATURE DEVICE',hero:'/medical-hero/ear.jpg',lead:'从真实握持出发，让测量更自然、更明确。',intro:'面向家庭和医疗机构两类场景，结合成年人手部尺寸、探头角度与昼夜使用条件，优化握持舒适性、操作识别和产品亲和力。',images:['/medical/page-041.webp','/medical/page-048.webp']},
 cbct:{no:'03',title:'CBCT口腔\n扫描仪',en:'DENTAL CBCT SCANNER',hero:'/medical-hero/cbct.jpg',lead:'协调大型设备、操作者与被测者之间的关系。',intro:'围绕站姿、坐姿和多模式扫描流程，建立悬臂运动、整机升降、下颌托与把手细节，使专业设备具备清晰、可靠且友好的体验。',images:['/medical/page-056.webp','/medical/page-071.webp']},
 monitor:{no:'04',title:'母胎\n监护仪',en:'MATERNAL & FETAL MONITOR',hero:'/medical-hero/monitor.jpg',lead:'让复杂监护信息与临床操作保持清晰。',intro:'覆盖普通病房、手术室、ICU 与院内转运，优化观察角度、接口分布、设备携带和线缆管理，降低医护人员的操作负担。',images:['/medical-hero/monitor.jpg','/medical/page-096.webp']}
}
export default function LaserProject(){const slug=window.location.pathname.split('/').filter(Boolean).at(-1);const d=details[slug]||details.laser;return <main className="laser-detail"><nav className="medical-nav"><a href="/medical"><ArrowLeft size={17}/> BACK TO MEDICAL DESIGN</a><span>{d.no} / {d.en}</span><span>JIA ZILIANG / 2024—2025</span></nav><header className="laser-detail-hero"><img src={d.hero} alt={d.title.replace('\n','')} decoding="async"/><div/><section><p>MEDICAL PRODUCT / {d.no}</p><h1>{d.title.split('\n').map((line,i)=><span key={line}>{line}{i===0&&<br/>}</span>)}</h1><span>{d.en}</span></section></header><section className="laser-detail-intro medical-shell"><span>PROJECT OVERVIEW</span><h2>{d.lead}</h2><p>{d.intro}</p></section><section className="laser-detail-gallery medical-shell">{d.images.map((src,index)=><img src={src} alt={d.title.replace('\n','')} key={src} loading={index===0?'eager':'lazy'} decoding="async"/>)}</section><footer className="medical-footer"><a href="/medical"><ArrowLeft/> 返回医疗设备产品设计</a><span>© 2026 JIA ZILIANG</span></footer></main>}
